simulation_orchestrator:
  ros__parameters:
    num_agents: 5
    heartbeat_interval_ms: 100
    heartbeat_max_tick: 10              # Increased tolerance for network latency
    nodes_name_prefix: "agent_"
    agent_type: "ring"                    # Options: "bully", "hybrid_ring", ring"

chaos_monkey:
  ros__parameters:
    discovery_time_s: 0
    kill_interval_s: 10
    target_nodes_prefix: "agent_"
    reverse_order: false
