simulation_orchestrator:
  ros__parameters:
    num_agents: 10
    heartbeat_interval_ms: 500
    heartbeat_max_tick: 5              # Increased tolerance to gain network latency
    nodes_name_prefix: "agent_"
    agent_type: "hybrid_ring"     # Options: "bully", "hybrid_ring", ring, raft, benevolent_dictator"
    enable_traffic_logger: true        # Enable/Disable the traffic analysis logger
    
    # Chaos Monkey Settings
    enable_chaos_monkey: true
    chaos_monkey.kill_interval_s: 6   # increase the kill interval allows more time for recovery and reduce race condition issues
    chaos_monkey.discovery_time_s: 6
    chaos_monkey.reverse_order: true
    chaos_monkey.reduce_race_conditions: false

# chaos_monkey section is no longer used by standalone node, but orchestrator reads from above


# ----------------------------------- Notes -----------------------------------

# ----------------------------------- Bully -----------------------------------
#
#tested conditions:
#simulation_orchestrator:
#  ros__parameters:
#    num_agents: 10
#    heartbeat_interval_ms: 500
#    heartbeat_max_tick: 5              # Increased tolerance to gain network latency
#    nodes_name_prefix: "agent_"
#    agent_type: "bully"     # Options: "bully", "hybrid_ring", ring, raft, benevolent_dictator"
#    enable_traffic_logger: true        # Enable/Disable the traffic analysis logger
#    
#    # Chaos Monkey Settings
#    enable_chaos_monkey: true
#    chaos_monkey.kill_interval_s: 3
#    chaos_monkey.discovery_time_s: 3
#    chaos_monkey.reverse_order: false
#
# ----------------------------------- Hybrid Ring -----------------------------
#
# ----------------------------------- Ring ------------------------------------
# the real issue with the ring implementation is the overall complexity of racing conditions and parallel processes
#
# with ring implementation every dead node requires heartbeat_max_tick * heartbeat_interval_ms to be detected
# plus some extra time required for ros2 to affectively revive it
# plus 2/3 * heartbeat_max_tick * heartbeat_interval_ms to be restarted completely
# considering the comunication speed negligible compared to the heartbeat intervals
# meaning that for heartbeat_interval_ms = 1000 and heartbeat_max_tick = 9 the minimum time to revive a node is around 15s
#
# tested conditions:
# simulation_orchestrator:
#   ros__parameters:
#     num_agents: 10
#     heartbeat_interval_ms: 1000
#     heartbeat_max_tick: 9              # Increased tolerance for network latency
#     nodes_name_prefix: "agent_"
#     agent_type: "ring"                    # Options: "bully", "hybrid_ring", ring, raft, benevolent_dictator"
#     enable_traffic_logger: true        # Enable/Disable the traffic analysis logger
# 
#     # Chaos Monkey Settings
#     enable_chaos_monkey: true
#     chaos_monkey.kill_interval_s: 20
#     chaos_monkey.discovery_time_s: 5
#     chaos_monkey.reverse_order: false
#
# ----------------------------------- Raft -----------------------------------
#
# tested conditions:
# simulation_orchestrator:
#   ros__parameters:
#     num_agents: 10
#     heartbeat_interval_ms: 500
#     heartbeat_max_tick: 5
#     nodes_name_prefix: "agent_"
#     agent_type: "raft"     # Options: "bully", "hybrid_ring", ring, raft, benevolent_dictator"
#     enable_traffic_logger: true        # Enable/Disable the traffic analysis logger
# 
#     # Chaos Monkey Settings
#     enable_chaos_monkey: true
#     chaos_monkey.discovery_time_s: 3
#     chaos_monkey.kill_interval_s: 5 
#     chaos_monkey.reverse_order: true
# 
# ----------------------------------->
# the following configuration is quite facinating since the speed of recovery is very similar to the failure rate:
# simulation_orchestrator:
#   ros__parameters:
#     num_agents: 10
#     heartbeat_interval_ms: 500
#     heartbeat_max_tick: 5              # Increased tolerance for network latency
#     nodes_name_prefix: "agent_"
#     agent_type: "raft"     # Options: "bully", "hybrid_ring", ring, raft, benevolent_dictator"
#     enable_traffic_logger: true        # Enable/Disable the traffic analysis logger
# 
#     # Chaos Monkey Settings
#     enable_chaos_monkey: true
#     chaos_monkey.discovery_time_s: 3
#     chaos_monkey.kill_interval_s: 3 
#     chaos_monkey.reverse_order: true
# ----------------------------------- Benevolent Dictator --------------------
# once a follower node notices a leader failure it revives it, but only the first one that notices it
#
# tested conditions:
# simulation_orchestrator:
#   ros__parameters:
#     num_agents: 10
#     heartbeat_interval_ms: 500
#     heartbeat_max_tick: 5              # Increased tolerance for network latency
#     nodes_name_prefix: "agent_"
#     agent_type: "benevolent_dictator"     # Options: "bully", "hybrid_ring", ring, raft, benevolent_dictator"
#     enable_traffic_logger: true        # Enable/Disable the traffic analysis logger
# 
#     # Chaos Monkey Settings
#     enable_chaos_monkey: true
#     chaos_monkey.discovery_time_s: 3
#     chaos_monkey.kill_interval_s: 5 
#     chaos_monkey.reverse_order: true
# -----------------------------------------------------------------------------